!!python/object:argparse.Namespace
random_seed: 2021
is_training: 1
model_id: solar_48_48
model: PatchTST
data: Solar
root_path: ./dataset/Solar/
data_path: solar_AL.txt
features: M
target: OT
freq: h
checkpoints: ./checkpoints/
seq_len: 48
label_len: 48
pred_len: 48
fc_dropout: 0.05
head_dropout: 0.0
patch_len: 16
stride: 8
padding_patch: end
revin: 1
affine: 0
subtract_last: 0
decomposition: 0
kernel_size: 25
individual: 0
embed_type: 0
enc_in: 137
dec_in: 137
c_out: 137
d_model: 512
n_heads: 8
e_layers: 2
d_layers: 1
d_ff: 512
moving_avg: 25
factor: 1
distil: true
dropout: 0.05
embed: timeF
activation: gelu
output_attention: false
do_predict: false
num_workers: 10
itr: 1
train_epochs: 100
batch_size: 32
patience: 100
learning_rate: 0.0001
des: Exp
loss: mse
lradj: type3
pct_start: 0.3
use_amp: false
use_gpu: true
gpu: 0
use_multi_gpu: false
devices: 0,1,2,3
test_flop: false
